name: datetime
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.0.0
  form_field_validator: ^1.1.0
  flutter_launcher_icons: ^0.9.1
  intl: ^0.17.0
  shared_preferences: ^2.0.6

flutter_icons:
  image_path_android: "assets/icons/timex.png"
  # image_path_ios: "assets/icons/timex.png"
  android: true 
  # ios: true 
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/icons/